--- CRIAR BANCO DE DADOS
CREATE DATABASE bd_16_byciclon
GO
--- USAR BANCO DE DADOS 
USE bd_16_byciclon
GO
--- CRIA A TABELA TB_CLIENTE
CREATE TABLE tb_cliente(idcliente INT PRIMARY KEY IDENTITY (1,1), --- COLUNA NUMERICA DO TIPO AUTONUMERAÇÃO
idendereco INT NOT NULL,-- CAMPO NUMERICO PARA FK, NÃO NULO
idregional INT NOT NULL, -- CAMPO NUMERICO PARA FK, NAO NULO
nome VARCHAR(40) NOT NULL, -- CAMPO TEXTO, NÃO NULO
email VARCHAR(40) NOT NULL, -- CAMPO TEXTO, NÃO NULO
cpf VARCHAR(11) NOT NULL -- CAMPO TEXTO, NÃO NULO
);

--- CRIAR TABELA DE VENDEDORES
CREATE TABLE tb_vendedores (idvendedor INT PRIMARY KEY IDENTITY (1,1), --- COLUNA NUMERICA DO TIPO AUTONUMERAÇÃO
idendereco INT NOT NULL, -- CAMPO NUMERICO, NÃO NULO
idregional INT NOT NULL, -- CAMPO NUMERICO, NÃO NULO
nome VARCHAR(40) NOT NULL, -- CAMPO TEXTO, NAO NULO
email VARCHAR(30) NOT NULL, -- CAMPO TEXTO, NÃO NULO
cpf VARCHAR(11) NOT NULL -- CAMPO TEXTO, NÃO NULO
);

--- TABELA DE PRODUTOS
CREATE TABLE tb_produtos (idproduto INT PRIMARY KEY IDENTITY (1,1), -- COLUNA NUMERICA DO TIPO AUTONUMERAÇÃO
nome VARCHAR(255) NOT NULL, -- CAMPO TEXTO, NÃO NULO
linha VARCHAR(255) NOT NULL, -- CAMPO TEXTO, NÃO NULO
valorunitario MONEY NOT NULL -- CAMPO VALOR, NÃO NULO
);

--- TABELA PEDIDOS
CREATE TABLE tb_pedidos (idpedido INT PRIMARY KEY IDENTITY (1,1), -- COLUNA NUMERICA DO TIPO AUTONUMERAÇÃO
idcliente INT NOT NULL, -- CAMPO NUMERICO, NÃO NULO
idvendedor INT NOT NULL, -- CAMPO NUMERICO, NÃO NULO
datapedido DATE NOT NULL, -- CAMPO DATA, NÃO NULO
qtitens INT NOT NULL, -- CAMPO NUMERICO, NÃO NULO
valortotal MONEY NOT NULL -- CAMPO VALOR, NÃO NULO
);

--- TABELA ITENS PEDIDOS
CREATE TABLE tb_itens_pedidos (iditem INT PRIMARY KEY IDENTITY (1,1), -- COLUNA NUMERICA DO TIPO AUTONUMERAÇÃO
idpedido INT NOT NULL, --CAMPO NUMERICO, NÃO NULO
idproduto INT NOT NULL, --CAMPO NUMERICO, NÃO NULO
quantidade INT NOT NULL, -- CAMPO NUMERICO, NÃO NULO
precounitario MONEY NOT NULL, -- CAMPO VALOR, NÃO NULO
desconto MONEY NOT NULL -- CAMPO VALOR, NÃO NULO
);

--- TABELA DE REGIONAL
CREATE TABLE tb_regional (idregional INT PRIMARY KEY IDENTITY (1,1), -- COLUNA NUMERICA DO TIPO AUTONUMERAÇÃO
nomeregional VARCHAR(50) NOT NULL, -- CAMPO TEXTO, NÃO NULO LIMITADO A 50 CARACTERES
enderecoregional VARCHAR(255), -- CAMPO TEXTO, LIMITADO A 255 CARACTERES
telefoneregional VARCHAR (50) -- CAMPO TEXTO, LIMITADO A 50 CARACTERES
);

--- TABELA EDEREÇOS
CREATE TABLE tb_endereco(idendereco INT PRIMARY KEY IDENTITY (1,1), -- COLUNA NUMERICA DO TIPO AUTONUMERAÇÃO
pais VARCHAR (30) NOT NULL, -- CAMPO TEXTO, LIMITADO A 30 CARACTERES
uf VARCHAR (50) NOT NULL, -- CAMPO TEXTO, LIMITADO A 50 CARACTERES
cidade VARCHAR (50) NOT NULL, -- CAMPO TEXTO, LIMITADO A 50 CARACTERES
bairro VARCHAR (50) NOT NULL, -- CAMPO TEXTO, LIMITADO A 50 CARACTERES
rua VARCHAR (50) NOT NULL, -- CAMPO TEXTO, LIMITADO A 50 CARACTERES
numero INT NOT NULL -- CAMPO VALOR, NÃO NULO
);

--- TABELA TEMPORARIA
CREATE TABLE temporaria (coluna INT,
coluna2 INT
);