--- UTILIZAR DROP TABLE PARA EXCLUSÃO 

--- CHAVE DE USO DA TABELA 
USE bd_16_byciclon -- CHAVE PARA USO DA TABELA 
SELECT * FROM temporaria; -- CONSULTA DA TABELA

--- REMOVER COLUNA DA TABELA
ALTER TABLE temporaria -- ESCOLHENDO A TABELA
DROP COLUMN  coluna2 -- ESCOLHENDO A COLUNA A SER EXCLUIDA

-- CONSULTA DAS ALTERAÇÕES
SELECT * FROM temporaria;

--- EXCLUSÃO DA TABELA TEMPORARIA
DROP TABLE temporaria