USE bd_16_byciclon

--- RELACIONAMENTO TB_CLIENTE COM TB_ENDERECOS
ALTER TABLE tb_cliente -- ALTERANDO A TABELA
ADD CONSTRAINT fk__cliente_endereco -- RESTRI플O PARA CONECTAR
FOREIGN KEY (idendereco) REFERENCES tb_endereco (idendereco) --- CONECTA O ID_ENDERECO DA TABELA TB_CLIENTES A CHAVE PRIMARIA DA TABELA TB_ENDERECOS (IDENDERECO)

--- RELACIONAMENTO TB_CLIENTE COM TB_REGIONAL
ALTER TABLE tb_cliente -- ALTERANDO A TABELA
ADD CONSTRAINT fk_cliente_regional -- RESTRI플O PARA CONECTAR
FOREIGN KEY (idregional) REFERENCES tb_regional (idregional) -- CONECTA O IDREGIONAL DA TABELA TB_CLIENTES A CHAVE PRIMARIA DA TABELA TB_REGIONAL (IDREGIONAL)

--- RELACIONAMENTO TB_VENDEDORES COM TB_ENDERECOS
ALTER TABLE tb_vendedores -- ALTERANDO A TABELA
ADD CONSTRAINT fk_vendedores_endereco -- RESTRI플O PARA CONECTAR
FOREIGN KEY (idendereco) REFERENCES tb_endereco (idendereco) -- CONECTA O IDENDERECO DA TABELA TB_VENDEDORES A CHAVE PRIMARIA DA TABELA TB_ENDERECOS (IDENDERECOL)

--- RELACIONAMENTO TB_VENDEDORES COM TB _REGIONAL
ALTER TABLE tb_vendedores -- ALTERANDO A TABELA
ADD CONSTRAINT fk_vendedores_regional -- RESTRI플O PARA CONECTAR
FOREIGN KEY (idregional) REFERENCES tb_regional(idregional) -- CONECTA O IDREGIONAL DA TABELA TB_VENDEDORES A CHAVE PRIMARIA DA TABELA TB_REGIONAL(IDREGIONAL)

--- RELACIONAMENTO TB_PEDIDO COM TB_CLIENTE
ALTER TABLE tb_pedidos -- ALTERANDO A TABELA
ADD CONSTRAINT fk_pedido_cliente -- RESTRI플O PARA CONECTAR
FOREIGN KEY (idcliente) REFERENCES tb_cliente(idcliente) -- CONECTA O IDCLIENTE DA TABELA TB_PEDIDO A CHAVE PRIMARIA DA TABELA TB_CLIENTES(IDCLIENTE)

--- RELACIONAMENTO TB_PEDIDO COM TB_VENDEDORES
ALTER TABLE tb_pedidos -- ALTERANDO A TABELA
ADD CONSTRAINT fk_pedido_vendedores -- RESTRI플O PARA CONECTAR
FOREIGN KEY (idvendedor) REFERENCES tb_vendedores(idvendedor) -- CONECTA O IDVENDEDOR DA TABELA TB_PEDIDO A CHAVE PRIMARIA DA TABELA TB_VENDEDORES(IDVENDEDORES)

--- RELACIONAMENTO TB_ITENS_PEDIDO COM TB_PEDIDO
ALTER TABLE tb_itens_pedidos -- ALTERANDO A TABELA
ADD CONSTRAINT fk_itens_pedidos_pedido -- RESTRI플O PARA CONECTAR
FOREIGN KEY (idpedido) REFERENCES tb_pedidos (idpedido) -- CONECTA O IDVENDEDOR DA TABELA TB_ITENS_PEDIDO A CHAVE PRIMARIA DA TABELA TB_VENDEDORES(IDVENDEDORES)

--- RELACIONAMENTO TB_ITENS_PEDIDO COM TB_PRODUTOS
ALTER TABLE tb_itens_pedidos  -- ALTERANDO A TABELA
ADD CONSTRAINT fk_itens_pedidos_produtos -- RESTRI플O PARA CONECTAR
FOREIGN KEY (idproduto) REFERENCES tb_produtos(idproduto) -- CONECTA O IDPRODUTO DA TABELA TB_ITENS_PEDIDO A CHAVE PRIMARIA DA TABELA TB_PRODUTOS(IDPRODUTO)
