--- DADOS SOBRE A TABELA 
EXEC sp_help 'tb_produtos';

--- PROPRIEDADES DE UMA TABELA
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tb_pedidos';

-- CHAVE PRIMARIA DA TABELA
EXEC sp_pkeys 'tb_pedidos';

-- CHAVE ESTRANGEIRA DA TABELA
EXEC sp_fkeys 'tb_pedidos';

--- VER TODAS AS TABELAS DO NOSSO BANCO DE DADOS
SELECT name
FROM sys.tables
ORDER BY name;

--- VER TODAS AS TABELAS DO NOSSO BANCO DE DADOS POR ORDEM ASCENDENTE
SELECT name
FROM sys.tables
ORDER BY name ASC;

--- VER TODAS AS TABELAS DO NOSSO BANCO DE DADOS POR ORDEM DECRESCENTE
SELECT name
FROM sys.tables
ORDER BY name DESC;

--- VER A DISTRIBUIÇÃO DE VALORES (EX: POR CIDADE OU ESTADO)
SELECT cidade, COUNT (*) AS total
FROM tb_endereco
GROUP BY cidade
ORDER BY total DESC;

SELECT uf, COUNT (*) AS total
FROM tb_endereco
GROUP BY uf
ORDER BY total DESC;